steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/$PROJECT_ID/buildrunner:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f', 'Dockerfile.prereqs',
    '-t', 'gcr.io/$PROJECT_ID/buildrunner:latest',
    '--cache-from', 'gcr.io/$PROJECT_ID/buildrunner:latest',
    '.'
  ]
- name: gcr.io/cloud-builders/gsutil
  args: ['cp', 'gs://$PROJECT_ID/bazel-cache/cache-archive.tgz', '/workspace/cache-archive.tgz']
  volumes:
  - name: 'homevol'
    path: '/home'
- name: 'gcr.io/$PROJECT_ID/buildrunner:latest'
  args: ['./gcb-save-cache.sh --restore']
  volumes:
  - name: 'homevol'
    path: '/home'
#- name: 'gcr.io/$PROJECT_ID/buildrunner:latest'
    #  args: ['tools/deps/check_dependencies.sh']
#- name: 'gcr.io/$PROJECT_ID/buildrunner:latest'
#  args: ['tools/fix_formatting.sh']
- name: 'gcr.io/$PROJECT_ID/buildrunner:latest'
  args: ['./build.sh']
  env:
  - "ANDROID_HOME=/android_sdk/"
  volumes:
  - name: 'homevol'
    path: '/home'
- name: 'gcr.io/$PROJECT_ID/buildrunner:latest'
  args: ['./test.sh']
  env:
  - "ANDROID_HOME=/android_sdk/"
  volumes:
  - name: 'homevol'
    path: '/home'
- name: 'gcr.io/$PROJECT_ID/buildrunner:latest'
  args: ['./gcb-save-cache.sh']
  volumes:
  - name: 'homevol'
    path: '/home'
- name: gcr.io/cloud-builders/gsutil
  args: ['cp', '/workspace/cache-archive.tgz', 'gs://$PROJECT_ID/bazel-cache/']
  volumes:
  - name: 'homevol'
    path: '/home'
images: ['gcr.io/$PROJECT_ID/buildrunner:latest']
timeout: "20m"
options:
  machineType: N1_HIGHCPU_32
