FROM angular/ngcontainer:0.7.0

RUN sudo apt-get update && \
    sudo apt-get install --no-install-recommends -y \
                    yapf3 python3-pkg-resources libstdc++6 tree && \
	sudo ln -s /usr/bin/yapf3 /usr/bin/yapf

COPY tools/get_android_sdk.sh /get_android_sdk.sh
RUN sudo mkdir /android_sdk/ && sudo chmod a+rwx /android_sdk/ && /get_android_sdk.sh --force
